"""Regenerate the mermaid diagram embedded in README.md and docs/architecture.md.

The diagram is *generated from the compiled graph* —
``build_agent_graph(...).get_graph().draw_mermaid()`` — never drawn by
hand, so it can't silently disagree with ``graph.py``.
``tests/test_graph_diagram.py`` fails if the committed copies drift;
when it does, run:

    python scripts/render_graph_diagram.py
"""

from __future__ import annotations

import re
import sys
import tempfile
from pathlib import Path

from langchain_core.messages import AIMessage

from coding_agent.config import Settings
from coding_agent.graph import build_agent_graph

REPO = Path(__file__).resolve().parent.parent
DOCS_WITH_DIAGRAM = [REPO / "README.md", REPO / "docs" / "architecture.md"]

START = "<!-- graph-diagram:start (generated by scripts/render_graph_diagram.py) -->"
END = "<!-- graph-diagram:end -->"
BLOCK = re.compile(re.escape(START) + r".*?" + re.escape(END), re.DOTALL)


def current_mermaid() -> str:
    """Mermaid source for the parent graph, built with the fake provider."""
    with tempfile.TemporaryDirectory() as tmp:
        settings = Settings(
            provider="fake",
            workspace_root=Path(tmp) / "ws",
            trace_dir=Path(tmp) / "traces",
        )
        compiled = build_agent_graph(settings, fake_responses=[AIMessage(content="")])
        return compiled.get_graph().draw_mermaid().strip()


def render_block(mermaid: str) -> str:
    return f"{START}\n```mermaid\n{mermaid}\n```\n{END}"


def main() -> int:
    block = render_block(current_mermaid())
    for path in DOCS_WITH_DIAGRAM:
        text = path.read_text(encoding="utf-8")
        if not BLOCK.search(text):
            print(f"{path}: no diagram markers found", file=sys.stderr)
            return 1
        path.write_text(BLOCK.sub(lambda _: block, text), encoding="utf-8")
        print(f"updated {path.relative_to(REPO)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
